query GetCategoriesMenu {
    categories(filters: { parent_category_uid: { eq: "Mg==" } }) {
        items {
            uid
            name
            include_in_menu
            url_key
            products {
                total_count
            }
            children_count
            children {
                uid
                name
                level
                include_in_menu
                url_key
                products {
                    total_count
                }
                children_count
                children {
                    uid
                    name
                    level
                    include_in_menu
                    url_key 
                    products {
                        total_count
                    }
                    children_count
                    children {
                        uid
                        name
                        level
                        include_in_menu
                        url_key
                        products {
                            total_count
                        }
                        children_count
                        children {
                            uid
                            name
                            level
                            include_in_menu
                            url_key
                            products {
                                total_count
                            }
                        }
                    }
                }
            }
        }
        total_count
        page_info {
            current_page
            page_size
            total_pages
        }
    }
}
