query GetProductsByCategoryUid($uid: String!) {
  products(filter: {
    category_uid: { eq: $uid }
  }) {
    total_count
    aggregations {
      attribute_code
      label
      options {
        count
        label
        value
      }
    }
    sort_fields {
      default
      options {
        label
        value
      }
    }
    items {
      uid
      url_key
      name
      small_image {
        label
        url
      }
    }
  }
}